# Generated by Django 2.1.2 on 2020-08-18 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_1', models.CharField(blank=True, max_length=20, null=True, verbose_name='機種名')),
                ('sample_2', models.IntegerField(blank=True, null=True, verbose_name='収支')),
                ('sample_3', models.CharField(blank=True, max_length=8, null=True, verbose_name='年月')),
                ('sample_4', models.CharField(blank=True, max_length=50, null=True, verbose_name='作成者')),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='作成時間')),
            ],
            options={
                'verbose_name': 'スロット収支管理',
                'verbose_name_plural': 'スロット収支管理',
            },
        ),
    ]
