# Generated by Django 2.1.2 on 2020-08-13 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200813_1143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='item',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='item',
            name='updated_by',
        ),
        migrations.AlterField(
            model_name='item',
            name='sample_2',
            field=models.IntegerField(blank=True, null=True, verbose_name='収支'),
        ),
    ]
