# Generated by Django 2.1.2 on 2020-08-13 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200813_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='sample_3',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='年月'),
        ),
    ]
